### ISSUE TITLE
On Opening Settings Programm close itself

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/WoWDatabaseEditor#1]
I Pull the newest source ( c1c6c4e690cb91dbc06f6418ab7f3be501e3d435 ) and compile it but after start und go to the settings the programm load a few seconds and close itself.
Test it with release and debug version

**Comment by Faq** [comment]
gif or video would be nice.

**Comment by BAndysc** [comment]
Instructions on how to reproduce were clear :) Indeed, after latest changes I have made a bug when an user doesn’t have database settings already provided.

It should be fixed, could you please try now?
https://github.com/BAndysc/WoWDatabaseEditor/commit/7e7b7a207f2a75e1ff40c646230e226b05809b7f

**Comment by gonzo1247** [comment]
Yes its with https://github.com/TrinityCore/WoWDatabaseEditor/commit/7e7b7a207f2a75e1ff40c646230e226b05809b7f fixed
