### ISSUE TITLE
Float Value are not correct handled

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/WoWDatabaseEditor#2]
If you load any Creature and add a script that they should move to a position and set the X Y Z or O value they are in the most cases set to zero. (in some cases i see(but this was in the old version) that the set to a int.
![pos_issue_01](https://user-images.githubusercontent.com/640311/104580150-28b79800-565d-11eb-96d2-9f6c0d9df5f6.jpg)
![pos_issue_02](https://user-images.githubusercontent.com/640311/104580154-29e8c500-565d-11eb-98b8-cef7a765e702.jpg)
![pos_issue_03](https://user-images.githubusercontent.com/640311/104580155-29e8c500-565d-11eb-837d-28f4215fb522.jpg)
![pos_issue_04](https://user-images.githubusercontent.com/640311/104580157-29e8c500-565d-11eb-932f-c37340f6b15f.jpg)

**Comment by BAndysc** [comment]
Hmm, I have just tested it (export sql, save sql, load sql) and it looks fine to me, can you please describe steps to reproduce?

When you change the float value (before you export) is it displayed properly in script view?

What is your decimal separator in your system? (do you use dot „.” or comma „,” for decimal part?)

**Comment by gonzo1247** [comment]
As decimal separator is in my system defined as comma (its a Windows in German language) 
If i use comma instead of a dot, the values are changed from: 12,1 to 0.121 but go i into the field, that looks like 121

https://user-images.githubusercontent.com/640311/104585529-6d92fd00-5664-11eb-948d-6c53b21b35d6.mp4


https://user-images.githubusercontent.com/640311/104585556-771c6500-5664-11eb-8797-c1e3cf80fe4d.mp4

**Comment by BAndysc** [comment]
Indeed, float values were hacked in target editing. In https://github.com/TrinityCore/WoWDatabaseEditor/commit/49c8d311a176298640e07aef85b42b03608ce1ed this should work as expected.

Thanks for the report
