### ISSUE TITLE
Gameobject Scriptview endless loading

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/WoWDatabaseEditor#4]
If you select a Gameobject and double click it in the Solution Explorer to open the Script View windows that open but its endless loading. Test it with Gameobject: 1587 - in Scriptview windows looks: Turkey Leg (loading) and in the middle of the screen is the loading symbol. You can nothing doing only close the window.
I test it with some different Gameobjects and by all the same problem.

**Comment by gonzo1247** [comment]
Edit: that problem appears also on Quests, Spell/Aura and Timed Action list

**Comment by BAndysc** [comment]
Could you please tell me what does appear in the panel when you click „{} tasks running in the background”?
<img width="318" alt="Zrzut ekranu 2021-01-14 o 23 06 09" src="https://user-images.githubusercontent.com/5689666/104659775-2dac3400-56bd-11eb-9a40-5773d39fc6b2.png">

What database version did you connect (wrath or shadowlands), did you setup DBC path? (currently they load for a very long time and the script cannot load until dbc is loaded)

**Comment by gonzo1247** [comment]
Yes i setup the DBC path, connectet db is shadowlands.
![loading_issue](https://user-images.githubusercontent.com/640311/104664642-0f9bff00-56d0-11eb-8e4f-7bddfad0f5bc.jpg)

**Comment by gonzo1247** [comment]
ok looks like that was the problem with the dbc loading, after a few restart the programm its now works

**Comment by BAndysc** [comment]
What DBC version did you load? DBC support wasn’t yet rewritten and it is working rather poorly now. I am testing cata dbc right now and is usable, but don’t know about the others.

**Comment by gonzo1247** [comment]
i use 335 and cata dbcs
