### ISSUE TITLE
Timed Action Lists list creature smart scripts instead of action lists

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/WoWDatabaseEditor#7]
**Describe the bug**
When trying to load a timed action list via quickload, the loading window lists creature smart scripts instead of timed action lists. Though you still can load the action lists by adding the value to the search bar, there wont be any search results as the list does not contain action lists at all.

**Version (commit hash)**
7afcb458c0cd45a1f3e0f51457f090512ee8645c

**To Reproduce**
1. Hit the timed action list button on the quickload menu
2. See that the entries of the popping up list are no timed action lists

**Expected behavior**
The load list should contain timed action lists instead of creature smart scripts

**Comment by funjoker** [comment]
Fixed in https://github.com/BAndysc/WoWDatabaseEditor/commit/b2d93720974f2c0bd1d232ab77779dce944b393e
