### ISSUE TITLE
Source and Action target types are missing entries

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/WoWDatabaseEditor#8]
**Describe the bug**
Several target types that are provided in the targets.json are not being shown as available target options in the UI.

**Version (commit hash)**
7afcb458c0cd45a1f3e0f51457f090512ee8645c

**To Reproduce**
1. Just create some random smart script and create a cast spell action.
2. Open up the target or source selection and notice there are alot of actions missing from the list despite being in the json file

**Expected behavior**
The selection should provide all targets given for the specified emulator. All these missing targets should be available for the cataclysm project as well

**Screenshots**
![image](https://user-images.githubusercontent.com/18347559/123065112-2711ad80-d40f-11eb-9530-3fe355d7af07.png)

**Comment by BAndysc** [comment]
Thanks for the report, do you remember if it was timed action list script?

I think these targets are visible when editing creature/gobject script, but missing in timed action list (which indeed is a bug)

**Comment by Ovahlord** [comment]
Yes, it was a timed action list
